# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rUfcz11EI2zIVslYOPytEGNaK6REtXln
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Replace with your actual file name after uploading
df = pd.read_csv('E-commerce.csv')
df.head()

df.info()

# See summary statistics
df.describe()

# Check for null values
df.isnull().sum()

df['Satisfaction Level'].fillna('Unknown', inplace=True)

# Encode Gender
df['Gender_Encoded'] = df['Gender'].map({'Male': 0, 'Female': 1})

# Encode Membership Type
df['Membership_Encoded'] = pd.factorize(df['Membership Type'])[0]

# Encode City
df['City_Encoded'] = pd.factorize(df['City'])[0]

# Encode Satisfaction Level
df['Satisfaction_Encoded'] = pd.factorize(df['Satisfaction Level'])[0]

# Create a new column: Spend per Item
df['Spend_Per_Item'] = df['Total Spend'] / df['Items Purchased']

# Create a new column: Engagement Score (basic example)
df['Engagement_Score'] = df['Average Rating'] * (1 / (df['Days Since Last Purchase'] + 1))

df.to_csv('transformed_customer_behavior.csv', index=False)

# Download the file from Colab
files.download('transformed_customer_behavior.csv')

print(df.groupby('City')['Total Spend'].mean().sort_values(ascending=False))

# Membership type by satisfaction
print(df.groupby('Membership Type')['Satisfaction Level'].value_counts(normalize=True))

# Average Spend vs. Engagement Score
import matplotlib.pyplot as plt

plt.scatter(df['Spend_Per_Item'], df['Engagement_Score'])
plt.xlabel('Spend Per Item')
plt.ylabel('Engagement Score')
plt.title('Engagement vs Spending')
plt.show()

